title: Quoke
author: Joshua Byrd
email: phocks@gmail.com
description: > # this means to ignore newlines until the next thing
  This is an openly editable repository for famous quotations
  about different things in the world.

twitter_username: phocks
github_username: phocks

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
# theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# permalink: /:title.html

plugins:
  - jekyll-coffeescript
  # - bootstrap

# gems: [jekyll-coffeescript]

collections:
  quotations:
    output: true
    permalink: /quotes/:name
  users:
    output: true
    permalink: /@:name